<?php
$labels = array();
$labels['shownotifies'] = '데스크탑 알림';
$labels['onlynew'] = '새로운 메시지만';
$labels['conf_browser'] = '브라우저 설정';
$labels['test_browser'] = '테스트';
$labels['excluded_directories'] = '폴더들을 제외한 알림';
$labels['check_ok'] = '브라우저 세팅이 잘 되었습니다.';
$labels['check_fail'] = '알림 설정이 불가합니다. "브라우저 설정"을 클릭해주세요.';
$labels['check_fail_blocked'] = '브라우저가 알림을 중지했습니다. 브라우저 설정에서 권한을 세팅해주세요.';
$labels['no_notifications'] = '브라우저가 데스크탑 알림을 지원하지 않습니다.';
$labels['ok_notifications'] = '이미 권한을 가지고 있습니다. 데스크탑 알림이 정상적으로 작동할 것입니다.';
$labels['notification_title'] = '[from]에게서 새로운 메일 도착';

$labels['seconds'] = '사운드';
$labels['off'] = '중지';
$labels['durable'] = '주기';

$labels['no_mailbox'] = '메일함을 보여주지 않습니다.';
$labels['short_mailbox'] = '짧게 메일함을 보여줍니다 ';
$labels['full_mailbox'] = '메일함 전체 이름을 보여줍니다.';

$labels['notifier_popuptype'] = '알림 클릭시 메시지 보기 형태';
$labels['new_tab'] = '새로운 탭';
$labels['new_window'] = '새로운 윈도우';
?>
